#!/usr/bin/env python
# encoding=gbk

import cv2
import matplotlib.pyplot as plt

if __name__ == "__main__":
    path = "../../image/lenna.png"
    gray = cv2.imread(path,0)
    'soble'
    img_soble_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, 3)
    img_soble_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, 3)

    'Laplace'
    img_laplace = cv2.Laplacian(gray, cv2.CV_64F, ksize=3)

    'canny'
    img_canny = cv2.Canny(gray, 50, 200)

    plt.subplot(231), plt.imshow(gray, "gray"), plt.title("Original")
    plt.subplot(232), plt.imshow(img_soble_x, "gray"), plt.title("soble_x")
    plt.subplot(233), plt.imshow(img_soble_y, "gray"), plt.title("soble_y")
    plt.subplot(234), plt.imshow(img_laplace, "gray"), plt.title("laplace")
    plt.subplot(235), plt.imshow(img_canny, "gray"), plt.title("canny")

    plt.show()

